dist: bionic
branches:
    only:
    - master
language: java
jdk:
  - openjdk11
cache:
    directories:
    - "$HOME/.m2"
jobs:
    include:
        - stage: test
          script:
            - cd karaf-system
            - mvn versions:set -DnewVersion=1.0.$TRAVIS_BUILD_NUMBER
            - mvn clean install -Pdev-build
          name: "Build & Test"
stages:
- name: test
  if: type = pull_request OR type = cron