FROM openjdk:11
ENV KARAF_INSTALL_PATH /opt
ENV KARAF_HOME $KARAF_INSTALL_PATH/patlego.vm

WORKDIR $KARAF_HOME
ADD patlego.vm/ .

ENV PATH $PATH:$KARAF_HOME/bin
EXPOSE 8101 1099 44444 8181
CMD ["karaf", "run"]