version: '3.4'
services:
  karaf:
     environment:
       - TZ=America/Montreal
     build: ./karaf 
     restart: always
     ports:
         - "5005:5005"
         - "8181:8181"
         - "8101:8101"
         - "1099:1099"
         - "44444:44444"
     volumes: 
      - ./pat-lego.vm/:/opt/karaf
     depends_on: 
      - postgres-db
     links: 
      - postgres-db
     networks: 
      - backend
  postgres-db:
     image: postgres:13 
     restart: always
     ports:
         - "5432:5432"
     environment: 
      - TZ=America/Montreal
      - POSTGRES_DB=karaf_db
      - POSTGRES_USER=karaf
      - POSTGRES_PASSWORD=karaf_pwd
     networks: 
      - backend
networks:
  backend:
    driver: bridge