version: '3.4'
services:
  karaf:
     environment:
       - TZ=America/Montreal
     build:
      context: ./
      dockerfile: Karaf.Dockerfile
     image: 525939336058.dkr.ecr.ca-central-1.amazonaws.com/pat-lego.vm.dev:karaf-vm
     restart: always
     ports:
         - "5005:5005"
         - "8181:8181"
         - "8101:8101"
         - "1099:1099"
         - "44444:44444"
     volumes: 
      - ./patlego.vm/:/opt/patlego.vm
      - ~/.m2/repository:/home/root/.m2/repository
     depends_on: 
      - postgres-db
     links: 
      - postgres-db
     networks: 
      - backend
  postgres-db:
     build:
      context: ./
      dockerfile: Postgres.Dockerfile
     image: 525939336058.dkr.ecr.ca-central-1.amazonaws.com/pat-lego.vm.dev:karaf-db
     restart: always
     ports:
         - "5432:5432"
     environment: 
      - TZ=America/Montreal
      - POSTGRES_DB=karaf_db
      - POSTGRES_USER=karaf
      - POSTGRES_PASSWORD=karaf_pwd
     volumes:
       - ./sql/init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
     networks: 
      - backend
networks:
  backend:
    driver: bridge