name: Manual Deploy to ECS Updates
on:
  workflow_dispatch
jobs:
  build_and_deploy:
    name: Deploy new container to ECS
    runs-on: ubuntu-latest
    steps:
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          architecture: x64
      - name: Get System
        run: mvn --settings settings.xml dependency:get -DgroupId=io.github.vm.patlego -DartifactId=core.kernel -Dversion=1.0-SNAPSHOT -Dpackaging=zip -DremoteRepositories=patlego-core::::https://maven.pkg.github.com/pat-lego/io.github.vm.patlego -Ddest=.
        env:
          KARAF_DB_PWD: ${{secrets.KARAF_DB_PWD}}
          KARAF_PWD: ${{secrets.KARAF_PWD}}
          PACKAGES_WEBSITE_TOKEN: ${{secrets.PACKAGES_WEBSITE_TOKEN}}
          PACKAGES_HTML_TOKEN: ${{secrets.PACKAGES_HTML_TOKEN}}
          PACKAGES_CORE_TOKEN: ${{secrets.PACKAGES_CORE_TOKEN}}
          PACKAGES_IOT_TOKEN: ${{secrets.PACKAGES_IOT_TOKEN}}
      - name: Unzip and Prepare
        run: | 
          # /home/runner/work/io.github.vm.patlego/io.github.vm.patlego

          # Unzip Karaf
          unzip core.kernel-1.0-SNAPSHOT.zip

          # Move unzipped folder
          mv /home/runner/work/io.github.vm.patlego/io.github.vm.patlego/patlego.vm /home/runner/work/io.github.vm.patlego/io.github.vm.patlego/patlego.vm-wrapper
          cd /home/runner/work/io.github.vm.patlego/io.github.vm.patlego/patlego.vm-wrapper
          mv patlego.vm /home/runner/work/io.github.vm.patlego/io.github.vm.patlego
          cd /home/runner/work/io.github.vm.patlego/io.github.vm.patlego

          ls
      - name: Build Image
        run: mvn clean install --file karaf-system/system.core/pom.xml --projects aws.image -Paws-build -Dkaraf.pwd=$KARAF_PWD
        env:
          KARAF_DB_PWD: ${{secrets.KARAF_DB_PWD}}
          KARAF_PWD: ${{secrets.KARAF_PWD}}
          PACKAGES_WEBSITE_TOKEN: ${{secrets.PACKAGES_WEBSITE_TOKEN}}
          PACKAGES_HTML_TOKEN: ${{secrets.PACKAGES_HTML_TOKEN}}
          PACKAGES_CORE_TOKEN: ${{secrets.PACKAGES_CORE_TOKEN}}
          PACKAGES_IOT_TOKEN: ${{secrets.PACKAGES_IOT_TOKEN}}
